### PR TITLE
Add missing specification of extension to gemspec

### PR DESCRIPTION
**Pull request by 2maz**

### CODE REVIEW

**Comment by marvin2k** [comment]
And this is the only file missing? Well then there is only the obvious left to be mentioned:

bla

**Comment by doudou** [comment]
Mmmm ... This was a repository that I created to split the ext part of utilrb into something else, but was never released / integrated in Rock. Do you _really_ need it for something ?

**Comment by 2maz** [comment]
I  rechecked why I am missing the extension in my installation if you say it should not:
so for preparation of the deb packages I am using the HEAD of utilrb, so there you already removed the C extension, and in order to make this repo (utilrb-ext) usable with gem2deb I require the extension to be given in the spec file.

**Comment by doudou** [comment]
None of the rock-core packages need the extension anymore on master (the only remaining user of ValueSet is Roby and Roby master provides it). The utilrb-ext package is not even defined in the rock.core and rock package sets.

So ... are you using it in your private repositories ?

**Comment by 2maz** [comment]
Yep, that is only a local adaption. Currently checking the build after removal of that adaption -- I was probably missing the 'moved to roby'-information.

**Pull request closed without merging**
